export const ocjeneTypes = {
  UCITAJ_OCJENE_REQUEST: 'UCITAJ_OCJENE_REQUEST',
  UCITAJ_OCJENE_SUCCESS: 'UCITAJ_OCJENE_SUCCESS',
  UCITAJ_OCJENE_ERROR: 'UCITAJ_OCJENE_ERROR',

  UCITAJ_OCJENU_REQUEST: 'UCITAJ_OCJENU_REQUEST',
  UCITAJ_OCJENU_SUCCESS: 'UCITAJ_OCJENU_SUCCESS',
  UCITAJ_OCJENU_ERROR: 'UCITAJ_OCJENU_ERROR',
};
