export const ocjeneTypes = {
  UCITAJ_OCJENE_REQUEST: 'UCITAJ_OCJENE_REQUEST',
  UCITAJ_OCJENE_SUCCESS: 'UCITAJ_OCJENE_SUCCESS',
  UCITAJ_OCJENE_ERROR: 'UCITAJ_OCJENE_ERROR',

  UCITAJ_OCJENU_REQUEST: 'UCITAJ_OCJENU_REQUEST',
  UCITAJ_OCJENU_SUCCESS: 'UCITAJ_OCJENU_SUCCESS',
  UCITAJ_OCJENU_ERROR: 'UCITAJ_OCJENU_ERROR',

  OBRISI_OCJENU_REQUEST: 'OBRISI_OCJENU_REQUEST',
  OBRISI_OCJENU_SUCCESS: 'OBRISI_OCJENU_SUCCESS',
  OBRISI_OCJENU_ERROR: 'OBRISI_OCJENU_ERROR',

  UREDI_OCJENU_REQUEST: 'UREDI_OCJENU_REQUEST',
  UREDI_OCJENU_SUCCESS: 'UREDI_OCJENU_SUCCESS',
  UREDI_OCJENU_ERROR: 'UREDI_OCJENU_ERROR',

  DODAJ_OCJENU_REQUEST: 'DODAJ_OCJENU_REQUEST',
  DODAJ_OCJENU_SUCCESS: 'DODAJ_OCJENU_SUCCESS',
  DODAJ_OCJENU_ERROR: 'DODAJ_OCJENU_ERROR',
};
