export const ucenikRazredTypes = {
  DODAJ_UCENIKA_U_RAZRED_REQUEST: 'DODAJ_UCENIKA_U_RAZRED_REQUEST',
  DODAJ_UCENIKA_U_RAZRED_SUCCESS: 'DODAJ_UCENIKA_U_RAZRED_SUCCESS',
  DODAJ_UCENIKA_U_RAZRED_ERROR: 'DODAJ_UCENIKA_U_RAZRED_ERROR',

  UCITAJ_UCENIKE_IZ_RAZREDA_REQUEST: 'UCITAJ_UCENIKE_IZ_RAZREDA_REQUEST',
  UCITAJ_UCENIKE_IZ_RAZREDA_SUCCESS: 'UCITAJ_UCENIKE_IZ_RAZREDA_SUCCESS',
  UCITAJ_UCENIKE_IZ_RAZREDA_ERROR: 'UCITAJ_UCENIKE_IZ_RAZREDA_ERROR',
};
