export const skolskeGodineTypes = {
  UCITAJ_SKOLSKE_GODINE_REQUEST: 'UCITAJ_SKOLSKE_GODINE_REQUEST',
  UCITAJ_SKOLSKE_GODINE_SUCCESS: 'UCITAJ_SKOLSKE_GODINE_SUCCESS',
  UCITAJ_SKOLSKE_GODINE_ERROR: 'UCITAJ_SKOLSKE_GODINE_ERROR',

  UCITAJ_SKOLSKU_GODINU_REQUEST: 'UCITAJ_SKOLSKU_GODINU_REQUEST',
  UCITAJ_SKOLSKU_GODINU_SUCCESS: 'UCITAJ_SKOLSKU_GODINU_SUCCESS',
  UCITAJ_SKOLSKU_GODINU_ERROR: 'UCITAJ_SKOLSKU_GODINU_ERROR',

  OBRISI_SKOLSKU_GODINU_REQUEST: 'OBRISI_SKOLSKU_GODINU_REQUEST',
  OBRISI_SKOLSKU_GODINU_SUCCESS: 'OBRISI_SKOLSKU_GODINU_SUCCESS',
  OBRISI_SKOLSKU_GODINU_ERROR: 'OBRISI_SKOLSKU_GODINU_ERROR',

  DODAJ_SKOLSKU_GODINU_REQUEST: 'DODAJ_SKOLSKU_GODINU_REQUEST',
  DODAJ_SKOLSKU_GODINU_SUCCESS: 'DODAJ_SKOLSKU_GODINU_SUCCESS',
  DODAJ_SKOLSKU_GODINU_ERROR: 'DODAJ_SKOLSKU_GODINU_ERROR',

  UREDI_SKOLSKU_GODINU_REQUEST: 'UREDI_SKOLSKU_GODINU_REQUEST',
  UREDI_SKOLSKU_GODINU_SUCCESS: 'UREDI_SKOLSKU_GODINU_SUCCESS',
  UREDI_SKOLSKU_GODINU_ERROR: 'UREDI_SKOLSKU_GODINU_ERROR',
};
