export const zakljucneOcjeneTypes = {
  UCITAJ_ZAKLJUCNU_OCJENU_REQUEST: 'UCITAJ_ZAKLJUCNU_OCJENU_REQUEST',
  UCITAJ_ZAKLJUCNU_OCJENU_SUCCESS: 'UCITAJ_ZAKLJUCNU_OCJENU_SUCCESS',
  UCITAJ_ZAKLJUCNU_OCJENU_ERROR: 'UCITAJ_ZAKLJUCNU_OCJENU_ERROR',

  OBRISI_ZAKLJUCNU_OCJENU_REQUEST: 'OBRISI_ZAKLJUCNU_OCJENU_REQUEST',
  OBRISI_ZAKLJUCNU_OCJENU_SUCCESS: 'OBRISI_ZAKLJUCNU_OCJENU_SUCCESS',
  OBRISI_ZAKLJUCNU_OCJENU_ERROR: 'OBRISI_ZAKLJUCNU_OCJENU_ERROR',

  DODAJ_ZAKLJUCNU_OCJENU_REQUEST: 'DODAJ_ZAKLJUCNU_OCJENU_REQUEST',
  DODAJ_ZAKLJUCNU_OCJENU_SUCCESS: 'DODAJ_ZAKLJUCNU_OCJENU_SUCCESS',
  DODAJ_ZAKLJUCNU_OCJENU_ERROR: 'DODAJ_ZAKLJUCNU_OCJENU_ERROR',

  UREDI_ZAKLJUCNU_OCJENU_REQUEST: 'UREDI_ZAKLJUCNU_OCJENU_REQUEST',
  UREDI_ZAKLJUCNU_OCJENU_SUCCESS: 'UREDI_ZAKLJUCNU_OCJENU_SUCCESS',
  UREDI_ZAKLJUCNU_OCJENU_ERROR: 'UREDI_ZAKLJUCNU_OCJENU_ERROR',
};
