export const nastavniciTypes = {
  UCITAJ_NASTAVNIKE_REQUEST: 'UCITAJ_NASTAVNIKE_REQUEST',
  UCITAJ_NASTAVNIKE_SUCCESS: 'UCITAJ_NASTAVNIKE_SUCCESS',
  UCITAJ_NASTAVNIKE_ERROR: 'UCITAJ_NASTAVNIKE_ERROR',

  UCITAJ_NASTAVNIKA_REQUEST: 'UCITAJ_NASTAVNIKA_REQUEST',
  UCITAJ_NASTAVNIKA_SUCCESS: 'UCITAJ_NASTAVNIKA_SUCCESS',
  UCITAJ_NASTAVNIKA_ERROR: 'UCITAJ_NASTAVNIKA_ERROR',

  OBRISI_NASTAVNIKA_REQUEST: 'OBRISI_NASTAVNIKA_REQUEST',
  OBRISI_NASTAVNIKA_SUCCESS: 'OBRISI_NASTAVNIKA_SUCCESS',
  OBRISI_NASTAVNIKA_ERROR: 'OBRISI_NASTAVNIKA_ERROR',

  DODAJ_NASTAVNIKA_REQUEST: 'DODAJ_NASTAVNIKA_REQUEST',
  DODAJ_NASTAVNIKA_SUCCESS: 'DODAJ_NASTAVNIKA_SUCCESS',
  DODAJ_NASTAVNIKA_ERROR: 'DODAJ_NASTAVNIKA_ERROR',

  UREDI_NASTAVNIKA_REQUEST: 'UREDI_NASTAVNIKA_REQUEST',
  UREDI_NASTAVNIKA_SUCCESS: 'UREDI_NASTAVNIKA_SUCCESS',
  UREDI_NASTAVNIKA_ERROR: 'UREDI_NASTAVNIKA_ERROR',
};
