export const nastavniciTypes = {
  UCITAJ_NASTAVNIKE_REQUEST: 'UCITAJ_NASTAVNIKE_REQUEST',
  UCITAJ_NASTAVNIKE_SUCCESS: 'UCITAJ_NASTAVNIKE_SUCCESS',
  UCITAJ_NASTAVNIKE_ERROR: 'UCITAJ_NASTAVNIKE_ERROR',

  OBRISI_NASTAVNIKA_REQUEST: 'OBRISI_NASTAVNIKA_REQUEST',
  OBRISI_NASTAVNIKA_SUCCESS: 'OBRISI_NASTAVNIKA_SUCCESS',
  OBRISI_NASTAVNIKA_ERROR: 'OBRISI_NASTAVNIKA_ERROR',
};
