export const uceniciTypes = {
  UCITAJ_UCENIKE_REQUEST: 'UCITAJ_UCENIKE_REQUEST',
  UCITAJ_UCENIKE_SUCCESS: 'UCITAJ_UCENIKE_SUCCESS',
  UCITAJ_UCENIKE_ERROR: 'UCITAJ_UCENIKE_ERROR',

  UCITAJ_UCENIKE_IZ_RAZREDA_REQUEST: 'UCITAJ_UCENIKE_IZ_RAZREDA_REQUEST',
  UCITAJ_UCENIKE_IZ_RAZREDA_SUCCESS: 'UCITAJ_UCENIKE_IZ_RAZREDA_SUCCESS',
  UCITAJ_UCENIKE_IZ_RAZREDA_ERROR: 'UCITAJ_UCENIKE_IZ_RAZREDA_ERROR',

  UCITAJ_UCENIKA_REQUEST: 'UCITAJ_UCENIKA_REQUEST',
  UCITAJ_UCENIKA_SUCCESS: 'UCITAJ_UCENIKA_SUCCESS',
  UCITAJ_UCENIKA_ERROR: 'UCITAJ_UCENIKA_ERROR',

  OBRISI_UCENIKA_REQUEST: 'OBRISI_UCENIKA_REQUEST',
  OBRISI_UCENIKA_SUCCESS: 'OBRISI_UCENIKA_SUCCESS',
  OBRISI_UCENIKA_ERROR: 'OBRISI_UCENIKA_ERROR',

  DODAJ_UCENIKA_REQUEST: 'DODAJ_UCENIKA_REQUEST',
  DODAJ_UCENIKA_SUCCESS: 'DODAJ_UCENIKA_SUCCESS',
  DODAJ_UCENIKA_ERROR: 'DODAJ_UCENIKA_ERROR',

  UREDI_UCENIKA_REQUEST: 'UREDI_UCENIKA_REQUEST',
  UREDI_UCENIKA_SUCCESS: 'UREDI_UCENIKA_SUCCESS',
  UREDI_UCENIKA_ERROR: 'UREDI_UCENIKA_ERROR',
};
