export const uceniciTypes = {
  UCITAJ_UCENIKE_REQUEST: 'UCITAJ_UCENIKE_REQUEST',
  UCITAJ_UCENIKE_SUCCESS: 'UCITAJ_UCENIKE_SUCCESS',
  UCITAJ_UCENIKE_ERROR: 'UCITAJ_UCENIKE_ERROR',

  UCITAJ_UCENIKA_REQUEST: 'UCITAJ_UCENIKA_REQUEST',
  UCITAJ_UCENIKA_SUCCESS: 'UCITAJ_UCENIKA_SUCCESS',
  UCITAJ_UCENIKA_ERROR: 'UCITAJ_UCENIKA_ERROR',
};
