export const predmetiTypes = {
  UCITAJ_PREDMETE_REQUEST: 'UCITAJ_PREDMETE_REQUEST',
  UCITAJ_PREDMETE_SUCCESS: 'UCITAJ_PREDMETE_SUCCESS',
  UCITAJ_PREDMETE_ERROR: 'UCITAJ_PREDMETE_ERROR',

  UCITAJ_PREDMET_REQUEST: 'UCITAJ_PREDMET_REQUEST',
  UCITAJ_PREDMET_SUCCESS: 'UCITAJ_PREDMET_SUCCESS',
  UCITAJ_PREDMET_ERROR: 'UCITAJ_PREDMET_ERROR',

  OBRISI_PREDMET_REQUEST: 'OBRISI_PREDMET_REQUEST',
  OBRISI_PREDMET_SUCCESS: 'OBRISI_PREDMET_SUCCESS',
  OBRISI_PREDMET_ERROR: 'OBRISI_PREDMET_ERROR',
};
