export const razrediSkolGodTypes = {
  UCITAJ_RAZREDE_IZ_SK_GOD_REQUEST: 'UCITAJ_RAZREDE_IZ_SK_GOD_REQUEST',
  UCITAJ_RAZREDE_IZ_SK_GOD_SUCCESS: 'UCITAJ_RAZREDE_IZ_SK_GOD_SUCCESS',
  UCITAJ_RAZREDE_IZ_SK_GOD_ERROR: 'UCITAJ_RAZREDE_IZ_SK_GOD_ERROR',
};
