export const razrediTypes = {
  UCITAJ_RAZREDE_REQUEST: 'UCITAJ_RAZREDE_REQUEST',
  UCITAJ_RAZREDE_SUCCESS: 'UCITAJ_RAZREDE_SUCCESS',
  UCITAJ_RAZREDE_ERROR: 'UCITAJ_RAZREDE_ERROR',

  /*   UCITAJ_RAZREDE_IZ_SKOLSKE_GODINE_REQUEST:
    'UCITAJ_RAZREDE_IZ_SKOLSKE_GODINE_REQUEST',
  UCITAJ_RAZREDE_IZ_SKOLSKE_GODINE_SUCCESS:
    'UCITAJ_RAZREDE_IZ_SKOLSKE_GODINE_SUCCESS',
  UCITAJ_RAZREDE_IZ_SKOLSKE_GODINE_ERROR:
    'UCITAJ_RAZREDE_IZ_SKOLSKE_GODINE_ERROR',
 */
  UCITAJ_RAZRED_REQUEST: 'UCITAJ_RAZRED_REQUEST',
  UCITAJ_RAZRED_SUCCESS: 'UCITAJ_RAZRED_SUCCESS',
  UCITAJ_RAZRED_ERROR: 'UCITAJ_RAZRED_ERROR',

  OBRISI_RAZRED_REQUEST: 'OBRISI_RAZRED_REQUEST',
  OBRISI_RAZRED_SUCCESS: 'OBRISI_RAZRED_SUCCESS',
  OBRISI_RAZRED_ERROR: 'OBRISI_RAZRED_ERROR',

  DODAJ_RAZRED_REQUEST: 'DODAJ_RAZRED_REQUEST',
  DODAJ_RAZRED_SUCCESS: 'DODAJ_RAZRED_SUCCESS',
  DODAJ_RAZRED_ERROR: 'DODAJ_RAZRED_ERROR',

  UREDI_RAZRED_REQUEST: 'UREDI_RAZRED_REQUEST',
  UREDI_RAZRED_SUCCESS: 'UREDI_RAZRED_SUCCESS',
  UREDI_RAZRED_ERROR: 'UREDI_RAZRED_ERROR',

  UCITAJ_UCENIKOVE_RAZREDE_REQUEST: 'UCITAJ_UCENIKOVE_RAZREDE_REQUEST',
  UCITAJ_UCENIKOVE_RAZREDE_SUCCESS: 'UCITAJ_UCENIKOVE_RAZREDE_SUCCESS',
  UCITAJ_UCENIKOVE_RAZREDE_ERROR: 'UCITAJ_UCENIKOVE_RAZREDE_ERROR',
};
